import sys
import os
from pathlib import Path

# Path manipulation to allow importing anim_gemini.project_drishti
# Assumes the script is in <workspace_root>/anim_gemini/outputs/generated_content/manim_scripts/
# And project_drishti is in <workspace_root>/anim_gemini/project_drishti/
# We add <workspace_root> to sys.path.
script_dir = Path(__file__).resolve().parent
# To reach <workspace_root> from e.g. /root/manim_gemini/anim_gemini/outputs/generated_content/manim_scripts/
# we go up 4 levels: manim_scripts -> generated_content -> outputs -> anim_gemini -> <workspace_root>
project_root_for_import = script_dir.parents[4] # <workspace_root>
if str(project_root_for_import) not in sys.path:
    sys.path.insert(0, str(project_root_for_import))

from manim import *
from anim_gemini.layout_utils import *
import numpy as np

class Scene1Non_Cooperation_Movement(Scene):
    def construct(self):
        # Scene: Non-Cooperation Movement
        # Narration: This is the narration for scene 1 concerning Non-Cooperation Movement. More details would be generated by an AI.
        # Mood/Color: #8B0000

        txt1 = create_smart_text("Non-Cooperation Movement",
                                                  zone_name="MAIN_CONTENT_AREA",
                                                  target_zone_width=10.24,
                                                  font_size=32,
                                                  max_font_size=48,
                                                  min_font_size=16)
        icon1 = create_smart_text("🖼  Icon", zone_name="MAIN_CONTENT_AREA", target_zone_width=10.24, font_size=32, color=LIGHT_GREY)
        shape1_shape_primitive = Rectangle(width=3.0, height=2.0, fill_color="BLUE", stroke_color="WHITE", fill_opacity=0.5, stroke_width=4)
        shape1_shape_primitive.scale_to_fit_width(10.24)
        if shape1_shape_primitive.height > 3.84:
            shape1_shape_primitive.scale_to_fit_height(3.84)
        shape1_shape_primitive.move_to(get_zone_center("MAIN_CONTENT_AREA"))
        shape1 = shape1_shape_primitive
        txt2 = create_smart_text("1920-1922",
                                                  zone_name="MAIN_CONTENT_AREA",
                                                  target_zone_width=10.24,
                                                  font_size=32,
                                                  max_font_size=48,
                                                  min_font_size=16)

        self.play(FadeIn(txt1, duration=1.5))
        self.play(DrawBorderThenFill(icon1, duration=2.0))
        self.play(Create(shape1, duration=1.0))
        self.play(Write(txt2, duration=1.0))
        self.wait(max(1, 7.0 - 4.50))